### ISSUE TITLE
Event Settings: Make Enable Event Referrals a premium feature

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#201]
![Screenshot 2024-11-18 131714](https://github.com/user-attachments/assets/bf4c51cf-3ff0-4d19-8511-21c4c8b6de66)

**Comment by ajax484** [comment]
Button is only enabled for paid accounts

![screenbud-ce4b4bf7-c4ac-4c56-a16f-8fe605404b2c](https://github.com/user-attachments/assets/db285f86-da1f-4584-9a32-29c8750d5ed1)
