### ISSUE TITLE
Make Enable self Check-in a premium feature

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#202]
![image](https://github.com/user-attachments/assets/711bf3ff-d376-4008-9263-fa92087c409c)

**Comment by ajax484** [comment]
Self check in is only available to paid accounts

![screenbud-869a51d6-0dcf-466a-9e43-0eb464f0981f](https://github.com/user-attachments/assets/73e43b4e-91c1-4909-a283-fbbfcae15e7e)
