### ISSUE TITLE
Red error toast shows when an attendee is added manually. also they do not receive emails. please make sure that all exsting rules are applied for the emails around join event and other bug fixes with the bulk upload

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#211]
![image](https://github.com/user-attachments/assets/20b40a6a-f0dd-4a51-a575-7d620f7420e7)

**Comment by ajax484** [comment]
![screenbud-36d3dcbc-c41a-4ccc-81dc-e20899fde971](https://github.com/user-attachments/assets/d1eba458-06fc-424f-8a31-5cd0a250c2aa)
