### ISSUE TITLE
Finx contact request UI: show only pending contacts when there is a pending contacts and not both

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#212]
![image](https://github.com/user-attachments/assets/a8ea73e7-3a7b-461f-912c-d1270069b791)

**Comment by ajax484** [comment]
![screenbud-48ba93d5-f7b0-4d8c-b7a3-07155032c12b](https://github.com/user-attachments/assets/2bfaa5a0-a11e-46e5-ae82-37ce0433b0d9)
