### ISSUE TITLE
session analytics: everything in the highlighted box isn't working

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#226]
![image](https://github.com/user-attachments/assets/26327b88-818e-4cd1-a150-bd9d94112efa)

**Comment by ajax484** [comment]
Fixed
![screenbud-a358b4fe-4a28-476c-b55e-bde14f5e4746](https://github.com/user-attachments/assets/05b73fc2-00e8-40dd-906a-8d07b7e8563e)
