### ISSUE TITLE
Average leads show NAN when there is no partner in the database for an event. use a defaulk value of 0 instead of NAN

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#227]
![image](https://github.com/user-attachments/assets/b0d1f409-620d-4782-adcd-d548d3adc6ea)

**Comment by ajax484** [comment]
fixed

![screenbud-8914f8df-7a5a-45f9-a804-3c667d08ef58](https://github.com/user-attachments/assets/d629fb5e-c3db-42ac-b2b0-bca2ecc91136)
