### ISSUE TITLE
Email received upon contact request shows undefined instead of organization name

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#229]
![image](https://github.com/user-attachments/assets/924640ed-cfc4-44fb-98dd-9351dec92871)

Also use black font colour for the body of the text.

**Comment by ajax484** [comment]
![screenbud-7c6a20ab-1520-4b8f-a052-da3ef1a07250](https://github.com/user-attachments/assets/6663ebed-de46-4bac-9a16-6a668c31e794)
