### ISSUE TITLE
Reception Agenda- Incomplete UI

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#232]
- [x] Speakers names no longer appear
- [x] Reception agenda: users still don't see join event button in mobile view. Maybe you should put it next to where the copy event link is

![image](https://github.com/user-attachments/assets/7bdccb3e-f09f-4d3a-ba7d-1bd6e88bbbcb)

**Comment by sekani50** [comment]
attempted
