### ISSUE TITLE
Reception Mobile minor adjustments

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#233]
- [x] Increase space above partners a bit
- [x] Increase space above Speakers a bit
- [x] When partners are not available or inactive don't show in mobile and desktop reception page

![WhatsApp Image 2024-11-21 at 18 33 14_648e6a38](https://github.com/user-attachments/assets/7b5ec6d2-4333-463f-8f40-2b645c14b573)

**Comment by sekani50** [comment]
attempted
