### ISSUE TITLE
agenda UI Issues

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#234]
- [x] agenda mobile: Include space in the speaker names

![image](https://github.com/user-attachments/assets/2fbc8429-5ca8-454c-8a5a-37755738f9aa)

- [x] show left and right navigation in the desktop version when an event is longer than 7 days
![image](https://github.com/user-attachments/assets/d05df424-5efb-499b-b925-3717d5763f54)

- [x] This error showed while I tried to update a speaker. It is updated but still shows error: 
![image](https://github.com/user-attachments/assets/4475d84c-a146-4321-9a57-5270ec733c8b)

- [x] Speakers inside an agenda page should be on one line each
![image](https://github.com/user-attachments/assets/23e9091d-4bbb-4cf7-a534-a8956469de54)

**Comment by sekani50** [comment]
attenpted

**Comment by kachiozo** [comment]
closed
