### ISSUE TITLE
Fix this marketing page's mobile view

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#266]
![image](https://github.com/user-attachments/assets/322a8b11-3a7f-40fb-a798-99e4ae33e5c6)

**Comment by ajax484** [comment]
![screenbud-8ff058d5-ace2-486b-9082-3e32225459c6](https://github.com/user-attachments/assets/ca83a9e1-dedf-4de2-88ee-d5df968991fb)
