### ISSUE TITLE
partner leads: this card is out of place

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#275]
![image](https://github.com/user-attachments/assets/929f394b-b14d-48c4-9f60-c8274c97bd0d)

**Comment by ajax484** [comment]
![screenbud-267abf07-ba56-4006-b097-e4ab55843d8f (1)](https://github.com/user-attachments/assets/ab38eb37-29eb-4c72-8d16-87911a364525)
