### ISSUE TITLE
Include export here: A lead should be able to export their data

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#276]
![image](https://github.com/user-attachments/assets/1ce2d090-07b0-46a4-86d9-346969b3490b)

**Comment by ajax484** [comment]
![screenbud-17db3d85-52e1-4a7e-ac41-e236a16578e9](https://github.com/user-attachments/assets/dc842cde-2da0-498f-9911-c00d4d6924b6)
