### ISSUE TITLE
Update attendee flow to join an event.

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#278]
We have achieved good progress with passwordless login to an event. However, we can't always get the event host to mandate event attendees to join an event using the join event button. Besides, attendees would want to enjoy some level of freedom in deciding which browser to join the event with.

To put this to context, I was in an event, where an event host shared the reception link with the attendees to join the event. Unfortunately, they couldn't access it, as you might already know why. 

Recall that the system first checks if you are signed in (otherwise, it starts authenticating or redirects you to the log-in page); if yes, it checks if you are a registered attendee (otherwise, it sends you to the event registration page).

The challenge here is that users may not always have passwords since they never created an account while registering for the event. Hence, there is now a need to allow new flexibility,

The requirement is simple. When the reception link is shared with anyone, check if they are signed in on Zikoro. If not, show this flow on the Figma page. If they are signed in but not registered, redirect them to the register for the event page

![image](https://github.com/user-attachments/assets/93392487-c4b2-41c1-a539-e7b6a7bea520)

https://www.figma.com/proto/FkN4ZKdXwaniK4zEpUS1lG/Zikoro_V2?node-id=1691-11388&node-type=frame&t=yGIIAlRb69vZFMwt-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=483%3A5254&show-proto-sidebar=1

**Comment by sekani50** [comment]
You did not talk about what will be sent to their mail. If it will be a code, are they going to use to code to login ? Or Are they now going to be forced to register? Or maybe they will see the password less link in their mail?
