### ISSUE TITLE
update the partner email to help the partners onboard better.

### ISSUE THREAD

**Issue by kachiozo** [Ozoemenamsolomon/zikoro#298]
replace the highlighted sentence with this. I have observed a lot of confussion with the aprtners.

To access your virtual booth, you need to be a registered attendee using this email: [partner registration email]. If you haven’t registered yet, please do so by following this link: [event registration link].

![image](https://github.com/user-attachments/assets/de900875-5cd4-42e1-961c-2739c0642bf4)

**Comment by sekani50** [comment]
attemoted
